# Generated by Django 4.1.2 on 2022-10-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
